"""Render a Memo into a Markdown research note and a standalone styled HTML memo."""
from __future__ import annotations

import html
from datetime import date

from .agents import Memo
from .models import Claim, KnowledgeBase


def _cite(claim: Claim) -> str:
    return f" [{claim.source}]" if claim.source else " [analyst view]"


# --------------------------------------------------------------------------- #
# Markdown
# --------------------------------------------------------------------------- #
def render_markdown(memo: Memo) -> str:
    kb = memo.kb
    v = memo.validation
    lines: list[str] = []
    a = lines.append

    a(f"# {kb.title}")
    a(f"*{kb.subtitle}*")
    a("")
    a(f"> **As of** {kb.as_of}  ·  **Generated by** AlphaThesis (an AlphaAnalyst extension)  ·  "
      f"**Citation coverage** {v.coverage*100:.0f}% ({v.cited_facts}/{v.fact_claims} fact-claims sourced)")
    a("")
    a(f"**One-liner.** {kb.one_liner}")
    a("")
    a("## Verdict")
    a(f"{memo.verdict}")
    a("")
    a(f"**Conviction:** {memo.conviction}")
    a("")

    a("## Bull thesis (constructive agents)")
    for p in memo.bull:
        a(f"### {p.name}")
        for c in p.claims:
            tag = f" `({c.value})`" if c.value else ""
            a(f"- {c.text}{tag}{_cite(c)}")
        a("")

    a("## Devil's Advocate (forced to disagree)")
    for r in memo.rebuttals:
        a(f"### {r.pillar}")
        for c in r.claims:
            a(f"- {c.text}{_cite(c)}")
        a("")
    if memo.blind_spots:
        a(f"> ⚠️ **Unchallenged bull pillars (blind spots):** {', '.join(memo.blind_spots)} — "
          f"no opposing evidence in the knowledge base; treat with caution.")
        a("")

    a("## Value chain")
    for e in kb.entities:
        srcs = "".join(f" [{s}]" for s in e.sources)
        a(f"- **{e.name}** — *{e.role}.* {e.note}{srcs}")
    a("")

    a("## What to monitor")
    for m in kb.monitorables:
        a(f"- {m}")
    a("")

    a("## Citation audit")
    a(f"- Total claims: **{v.total_claims}**  ·  Fact-claims: **{v.fact_claims}**  ·  "
      f"Sourced: **{v.cited_facts}**  ·  Opinion/inference: **{v.inference_claims}**")
    a(f"- Coverage: **{v.coverage*100:.0f}%**  ·  Validator: **{'PASS' if v.passed else 'FAIL'}**")
    if v.failures:
        for cid, reason in v.failures:
            a(f"  - ❌ {cid}: {reason}")
    a("")

    a("## Sources")
    for s in kb.sources.values():
        a(f"- {s.cite()}")
    a("")
    a("---")
    a("*Methodology: claims are extracted into a structured knowledge base; constructive "
      "agents build the bull pillars; a Devil's Advocate is forced to supply the bear case; "
      "a citation validator requires every numeric fact-claim to resolve to a real source, "
      "else it is flagged. Numbers are reproduced from cited public sources, not generated.*")
    return "\n".join(lines)


# --------------------------------------------------------------------------- #
# HTML
# --------------------------------------------------------------------------- #
def _esc(s: str) -> str:
    return html.escape(s, quote=False)


def _bi(en: str, zh: str | None) -> str:
    """Render a bilingual span pair toggled by the page language class."""
    zh = zh or en
    return f'<span class="en">{_esc(en)}</span><span class="zh">{_esc(zh)}</span>'


def _claim_html(c: Claim) -> str:
    val = f'<span class="val">{_esc(c.value)}</span>' if c.value else ""
    cite = (f'<sup class="cite">{c.source}</sup>' if c.source
            else '<sup class="cite op">analyst</sup>')
    return f"<li>{_bi(c.text, c.text_zh)} {val}{cite}</li>"


def render_html(memo: Memo) -> str:
    kb = memo.kb
    v = memo.validation
    badge = "PASS" if v.passed else "FAIL"
    badge_cls = "pass" if v.passed else "fail"

    bull_html = ""
    for p in memo.bull:
        items = "\n".join(_claim_html(c) for c in p.claims)
        bull_html += f"<h4>{_bi(p.name, kb.pillar_zh(p.name))}</h4><ul>{items}</ul>"

    bear_html = ""
    for r in memo.rebuttals:
        items = "\n".join(_claim_html(c) for c in r.claims)
        bear_html += f"<h4>{_bi(r.pillar, kb.pillar_zh(r.pillar))}</h4><ul>{items}</ul>"

    blind = ""
    if memo.blind_spots:
        en_names = ", ".join(memo.blind_spots)
        zh_names = ", ".join(kb.pillar_zh(b) for b in memo.blind_spots)
        blind = (f'<p class="warn">⚠️ '
                 f'{_bi("Unchallenged bull pillars (blind spots): " + en_names, "未被反驳的多头支柱(盲点): " + zh_names)}</p>')

    entities = "\n".join(
        f'<li><b>{_esc(e.name)}</b> — <i>{_bi(e.role, e.role_zh)}.</i> {_bi(e.note, e.note_zh)}'
        f'{"".join(f"<sup class=cite>{s}</sup>" for s in e.sources)}</li>'
        for e in kb.entities
    )

    zh_mon = kb.monitorables_zh or kb.monitorables
    monitor = "\n".join(
        f"<li>{_bi(en, zh_mon[i] if i < len(zh_mon) else en)}</li>"
        for i, en in enumerate(kb.monitorables)
    )

    sources = "\n".join(
        f'<li><b>{s.id}</b> — {_esc(s.publisher)}, "{_esc(s.title)}" ({_esc(s.date)}). '
        f'<a href="{_esc(s.url)}">{_esc(s.url)}</a></li>'
        for s in kb.sources.values()
    )
    failures = ""
    if v.failures:
        failures = "<ul>" + "".join(
            f"<li class=bad>{_esc(cid)}: {_esc(reason)}</li>" for cid, reason in v.failures
        ) + "</ul>"

    return f"""<!doctype html>
<html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{_esc(kb.title)}</title>
<style>
:root{{--ink:#1a1a1a;--muted:#6b7280;--line:#e5e7eb;--bull:#0f7b3f;--bear:#b4232a;--bg:#faf9f7;--accent:#1f3a5f;}}
*{{box-sizing:border-box}}
body{{margin:0;background:var(--bg);color:var(--ink);font:16px/1.6 -apple-system,"Segoe UI",Roboto,"PingFang SC",sans-serif;}}
.wrap{{max-width:860px;margin:0 auto;padding:48px 28px 80px;}}
h1{{font:600 30px/1.25 Georgia,"Songti SC",serif;margin:0 0 6px;}}
.sub{{color:var(--muted);font-style:italic;margin:0 0 18px;}}
.meta{{font-size:13px;color:var(--muted);border:1px solid var(--line);background:#fff;border-radius:10px;padding:12px 16px;margin-bottom:22px;}}
.badge{{display:inline-block;font-weight:700;font-size:12px;padding:2px 9px;border-radius:999px;margin-left:6px;}}
.badge.pass{{background:#e6f4ec;color:var(--bull);}}
.badge.fail{{background:#fae8e9;color:var(--bear);}}
h2{{font:600 21px/1.3 Georgia,serif;margin:34px 0 8px;padding-bottom:6px;border-bottom:2px solid var(--accent);}}
h4{{margin:16px 0 4px;font-size:15px;color:var(--accent);}}
.verdict{{background:#fff;border-left:4px solid var(--accent);border-radius:6px;padding:14px 18px;font-size:17px;}}
.conv{{color:var(--muted);font-size:14px;margin-top:6px;}}
.cols{{display:grid;grid-template-columns:1fr 1fr;gap:18px;}}
.card{{background:#fff;border:1px solid var(--line);border-radius:12px;padding:6px 18px 14px;}}
.card.bull{{border-top:3px solid var(--bull);}}
.card.bear{{border-top:3px solid var(--bear);}}
.card h3{{font-size:15px;letter-spacing:.04em;text-transform:uppercase;}}
.card.bull h3{{color:var(--bull);}} .card.bear h3{{color:var(--bear);}}
ul{{margin:6px 0 10px;padding-left:18px;}} li{{margin:6px 0;}}
.val{{display:inline-block;background:#eef2ff;color:var(--accent);font-weight:600;font-size:12px;
  padding:1px 6px;border-radius:5px;margin-left:2px;}}
sup.cite{{color:var(--accent);font-weight:700;font-size:11px;margin-left:2px;}}
sup.cite.op{{color:var(--muted);font-weight:600;}}
.warn{{background:#fff7ed;border:1px solid #fed7aa;color:#9a3412;padding:8px 12px;border-radius:8px;font-size:14px;}}
.bad{{color:var(--bear);}}
a{{color:var(--accent);word-break:break-all;}}
.foot{{margin-top:30px;color:var(--muted);font-size:13px;border-top:1px solid var(--line);padding-top:14px;}}
/* bilingual toggle */
.langbar{{position:fixed;top:14px;right:14px;z-index:50;display:flex;gap:0;border:1px solid var(--line);
  border-radius:999px;overflow:hidden;background:#fff;box-shadow:0 1px 4px rgba(0,0,0,.08);}}
.langbar button{{border:0;background:#fff;color:var(--muted);font:600 13px/1 -apple-system,sans-serif;
  padding:7px 14px;cursor:pointer;}}
.langbar button.active{{background:var(--accent);color:#fff;}}
.zh{{display:none;}}
body.lang-zh .en{{display:none;}}
body.lang-zh .zh{{display:inline;}}
@media(max-width:680px){{.cols{{grid-template-columns:1fr;}}}}
</style></head>
<body class="lang-en"><div class="langbar">
  <button id="b-en" class="active" onclick="setLang('en')">EN</button>
  <button id="b-zh" onclick="setLang('zh')">中文</button>
</div><div class="wrap">
  <h1>{_bi(kb.title, kb.title_zh)}</h1>
  <p class="sub">{_bi(kb.subtitle, kb.subtitle_zh)}</p>
  <div class="meta">{_bi("As of", "数据截至")} <b>{_esc(kb.as_of)}</b> ·
    {_bi("Generated by", "生成自")} <b>AlphaThesis</b> ({_bi("an AlphaAnalyst extension", "AlphaAnalyst 扩展")})
    · {_bi("Citation coverage", "引用覆盖率")} <b>{v.coverage*100:.0f}%</b> ({v.cited_facts}/{v.fact_claims})
    · {_bi("Validator", "校验")} <span class="badge {badge_cls}">{badge}</span></div>

  <p><b>{_bi("One-liner.", "一句话.")}</b> {_bi(kb.one_liner, kb.one_liner_zh)}</p>

  <h2>{_bi("Verdict", "结论")}</h2>
  <div class="verdict">{_bi(memo.verdict, memo.verdict_zh)}
    <div class="conv">{_bi("Conviction:", "信心:")} {_bi(memo.conviction, memo.conviction_zh)}</div></div>

  <h2>{_bi("Bull vs. Bear", "多空对照")}</h2>
  <div class="cols">
    <div class="card bull"><h3>{_bi("Bull thesis", "多头论点")}</h3>{bull_html}</div>
    <div class="card bear"><h3>{_bi("Devil's Advocate", "魔鬼代言人")}</h3>{bear_html}{blind}</div>
  </div>

  <h2>{_bi("Value chain", "价值链")}</h2><ul>{entities}</ul>
  <h2>{_bi("What to monitor", "监控清单")}</h2><ul>{monitor}</ul>

  <h2>{_bi("Citation audit", "引用审计")}</h2>
  <p>{_bi("Total claims", "总条目")} <b>{v.total_claims}</b> · {_bi("fact-claims", "事实条目")} <b>{v.fact_claims}</b> ·
     {_bi("sourced", "已引用")} <b>{v.cited_facts}</b> · {_bi("opinion", "观点")} <b>{v.inference_claims}</b> ·
     {_bi("coverage", "覆盖率")} <b>{v.coverage*100:.0f}%</b> · <span class="badge {badge_cls}">{badge}</span></p>
  {failures}

  <h2>{_bi("Sources", "来源")}</h2><ul>{sources}</ul>

  <p class="foot">{_bi(
    "Methodology: claims are extracted into a structured knowledge base; constructive agents build the bull pillars; a Devil's Advocate is forced to supply the bear case; a citation validator requires every numeric fact-claim to resolve to a real source, else it is flagged. Numbers are reproduced from cited public sources, not generated by the model.",
    "方法论:把 claim 抽取进结构化知识库;建设性 Agent 搭建多头支柱;Devil's Advocate 被强制提供空头论据;引用校验器要求每个数字型事实条目都必须映射到真实来源,否则标记。数字均转述自带引用的公开来源,而非模型生成。")}</p>
</div>
<script>
function setLang(l){{
  document.body.className = 'lang-' + l;
  document.getElementById('b-en').classList.toggle('active', l === 'en');
  document.getElementById('b-zh').classList.toggle('active', l === 'zh');
}}
</script>
</body></html>"""
